spring.application.name=BookIt
spring.data.mongodb.database=${env.MONGO_DATABASE}
spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
jwt.secret-key=${env.JWT_SECRET_KEY}
jwt.expiration=${env.JWT_EXPIRATION:86400000}
spring.sendgrid.api-key=${env.EMAIL_API_KEY}
aws.s3.bucket=${env.AWS_S3_BUCKET_NAME}
aws.accessKey=${env.AWS_ACCESS_KEY_ID}
aws.secretKey=${env.AWS_SECRET_ACCESS_KEY}
aws.region=${env.AWS_REGION}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB